common/models/Barang.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "barang".
 *
 * @property integer $id
 * @property string $nama_barang
 * @property integer $harga_beli
 * @property integer $harga_jual
 * @property string $satuan
 * @property integer $jumlah_barang
 * @property string $merk_barang
 * @property string $spesifikasi_barang
 * @property integer $id_user
 */
class Barang extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $imageFiles;
    public static function tableName()
    {
        return 'barang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama_barang', 'satuan', 'jumlah_barang', 'merk_barang', 'spesifikasi_barang', 'id_user','id_kategori','menu_barang','latar_foto'], 'required'],
            [[ 'jumlah_barang', 'id_user','id_kategori'], 'integer'],
          
            [['nama_barang', 'satuan', 'merk_barang','menu_barang','latar_foto'], 'string', 'max' => 255],
            [['imageFiles'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg', 'maxFiles' => 1],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama_barang' => 'Nama Barang',
            'menu_barang'=>'Menu Barang',
            'satuan' => 'Satuan',
            'jumlah_barang' => 'Jumlah Barang',
            'merk_barang' => 'Merk Barang',
           'id_kategori'=>'Kategori',
            'id_user' => 'Id User',
        ];
    }
}

backend/controllers/BarangController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Barang;
use common\models\BarangSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Url;
use yii\imagine\Image;

/**
 * BarangController implements the CRUD actions for Barang model.
 */
class BarangController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Barang models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BarangSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Barang model.
     * @param integer $id
     * @return mixed
     */

    public function actionDataKeterangan($id){
        $dataketerangan=\common\models\SpesifikasiBarang::find()->where(['id_barang'=>$id])->all();
        $dataukuran=\common\models\UkuranBarang::find()->where(['id'=>$id])->one();
        return $this->render('keterangan-barang', [
           'dataketerangan'=>$dataketerangan,
           'dataukuran'=>$dataukuran,
        ]);
    }
    public function actionKonfirmasiPemesanan($id){
        return $this->render('konfirmasi-barang', [
           
            ]);
    }
    public function actionPesanan(){

        return $this->render('pesanan-barang', [
           
        ]);
    }
    public function actionTambahKeterangan($id, $idbarang)
    {
        $modelfoto = new \common\models\FotoBarang();
        $modelketerangan = new \common\models\SpesifikasiBarang();
        if (Yii::$app->request->post('simpan') == 'true') {
            $modelketerangan->load(Yii::$app->request->post());
            $modelfoto->load(Yii::$app->request->post());
            $modelketerangan->id_barang = $id;
            $modelketerangan->save(false);
           
            $modelfoto->imageFiles = UploadedFile::getInstances($modelfoto, 'imageFiles');
            //  print_r($modelfoto);die();

            foreach ($modelfoto->imageFiles as $key => $val) {
                $modelfoto = new \common\models\FotoBarang();

                $imgName = rand(1, 1000) . $val->baseName . '.' . $val->getExtension();
                $modelfoto->foto = $imgName;
                $modelfoto->id_keterangan = $modelketerangan->id;
                $val->saveAs('img/fotobarang/' . $imgName);
                $modelfoto->save(false);
            }

            return $this->redirect(['view', 'id' => $idbarang]);
        }


        return $this->renderAjax('tambah-keterangan', [
            'modelfoto' => $modelfoto,
            'modelketerangan' => $modelketerangan,
        ]);
    }

    public function actionView($id)
    {
        $modelukuran = new \common\models\UkuranBarang();
        $modelfoto = new \common\models\FotoBarang();
        $modelketeranganukuran = new \common\models\SpesifikasiBarang();
        $databarang = Barang::find()->where(['id' => $id])->one();
        $dataukuran = \common\models\UkuranBarang::find()->where(['id_barang' => $id])->all();
        if (Yii::$app->request->post('simpan') == 'true') {
            $modelketeranganukuran->load(Yii::$app->request->post());
            $modelukuran->load(Yii::$app->request->post());
          //  print_r($modelukuran->harga_beli);die();
            $modelfoto->load(Yii::$app->request->post());
            $modelukuran->id_barang = $id;
            $modelukuran->save(false);
            $modelketeranganukuran->id_barang = $modelukuran->id;
            $modelketeranganukuran->save(false);
            $modelfoto->imageFiles = UploadedFile::getInstances($modelfoto, 'imageFiles');
            //  print_r($modelfoto);die();

            foreach ($modelfoto->imageFiles as $key => $val) {
                $modelfoto = new \common\models\FotoBarang();

                $imgName = rand(1, 1000) . $val->baseName . '.' . $val->getExtension();
                $modelfoto->foto = $imgName;
                $modelfoto->id_keterangan = $modelketeranganukuran->id;
                $val->saveAs('img/fotobarang/' . $imgName);
                $modelfoto->save(false);
            }

            $databarang->jumlah_barang = $modelukuran->jumlah_barang + $databarang->jumlah_barang;
            $databarang->save(false);
            return $this->redirect(['view', 'id' => $id]);
        }

        return $this->render('view', [
            'modelketeranganukuran' => $modelketeranganukuran,
            'model' => $this->findModel($id),
            'modelfoto' => $modelfoto,
            'modelukuran' => $modelukuran,
            'dataukuran' => $dataukuran,
        ]);
    }

    /**
     * Creates a new Barang model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $modelspesifikasibarang = new \common\models\SpesifikasiBarang();

        $model = new Barang();
        $model->id_user = \yii::$app->user->identity->id;

        if ($model->load(Yii::$app->request->post())) {
            $model->imageFiles = UploadedFile::getInstances($model, 'imageFiles');
            //  print_r($modelfoto);die();

            foreach ($model->imageFiles as $key => $val) {
                

                $imgName = rand(1, 1000) . $val->baseName . '.' . $val->getExtension();
                $model->latar_foto = $imgName;
               
                $val->saveAs('img/fotolatar/' . $imgName);
               
            }

            $model->jumlah_barang = 0;
            $model->save(false);

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'modelspesifikasibarang' => $modelspesifikasibarang,
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Barang model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Barang model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Barang model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Barang the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Barang::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/barang/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\money\MaskMoney;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $model common\models\Barang */
/* @var $form yii\bootstrap\ActiveForm */
?>
<div class="box">
    <div class="box-body">
        <div class="barang-form">

            <?php $form = ActiveForm::begin([
                // 'layout' => 'horizontal',
            ]); ?>

            <div class="row">
                <div class="col-md-6">
                    <?= $form->field($model, 'nama_barang')->textInput(['maxlength' => true]) ?>

                    <?= $form->field($model, 'menu_barang')->widget(\kartik\select2\Select2::classname(), [
                'data' => ArrayHelper::map(common\models\MenuBarang::find()->asArray()->all(), 'id', 'keterangan'),
                'language' => 'de',
                'options' => ['placeholder' => 'Pilih ...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]);
            ?>

                    <?= $form->field($model, 'satuan')->widget(\kartik\select2\Select2::classname(), [
                'data' => ArrayHelper::map(common\models\SatuanBarang::find()->asArray()->all(), 'id', 'keterangan'),
                'language' => 'de',
                'options' => ['placeholder' => 'Pilih Satuan...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]);
            ?>
             
                  
                   
                </div><div class="col-md-6">
                <?= $form->field($model, 'id_kategori')->widget(\kartik\select2\Select2::classname(), [
                'data' => ArrayHelper::map(common\models\KategoriBarang::find()->asArray()->all(), 'id', 'keterangan'),
                'language' => 'de',
                'options' => ['placeholder' => 'Pilih Satuan...'],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]);
            ?>
                <?= $form->field($model, 'merk_barang')->textInput(['maxlength' => true]) ?>
               
                   

                   
                   

                </div>
                <div class="col-md-6">
                    <?= $form->field($model, 'imageFiles')->label('Latar Foto')->fileInput(['multiple' => false,'accept' => 'image/*']) ?>


                </div>
            </div>

            <div class="col-lg-6">
                <div class="form-group">
                    <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                    <a href="./index" class="btn btn-default">Kembali</a>
                </div>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

backend/views/barang/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\BarangSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="barang-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nama_barang') ?>

    <?= $form->field($model, 'harga_beli') ?>

    <?= $form->field($model, 'harga_jual') ?>

    <?= $form->field($model, 'satuan') ?>

    <?php // echo $form->field($model, 'jumlah_barang') ?>

    <?php // echo $form->field($model, 'merk_barang') ?>

    <?php // echo $form->field($model, 'spesifikasi_barang') ?>

    <?php // echo $form->field($model, 'id_user') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/barang/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $model common\models\Barang */

$modelName = 'Barang';
$this->title = 'Input Barang';
$this->params['breadcrumbs'][] = ['label' => 'Barang', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box-header">
    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
</div>
<div class="box-body">
    <div class="row">
        <div class="col-lg-12">

            <div class="admin-create">

                <div class="barang-create">

                    <?= $this->render('_form', [
                        'modelspesifikasibarang' => $modelspesifikasibarang,
                        'model' => $model,
                    ]) ?>

                </div>


            </div>
        </div>
    </div>
</div>

backend/views/barang/header-menu.php
<?php

use yii\helpers\Html;
?>
<ul class="nav nav-tabs">
    <li class=""><?= Html::a('Data Barang', ['/barang']) ?></li>

    <li class=""><?= Html::a('Satuan Barang', ['/satuan-barang']) ?></li>

    <li class=""><?= Html::a('Kategori Barang', ['/kategori-barang']) ?></li>



</ul>

backend/views/barang/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\BarangSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Barang';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box-header">
    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
    <div class="pull-right">
        <a class="btn btn-primary btn-sm" href="<?= Url::toRoute(['create']) ?>">Tambahkan Data</a>
    </div>
</div>
<div class="box">
    <div class="box-body">
        <ul class="nav nav-tabs">
            <li class=""><?= Html::a('Data Barang', ['/barang']) ?></li>

            <li class=""><?= Html::a('Satuan Barang', ['/satuan-barang']) ?></li>

            <li class=""><?= Html::a('Kategori Barang', ['/kategori-barang']) ?></li>
            <li class=""><?= Html::a('Pesanan Barang', ['/barang/pesanan']) ?></li>
            <li class=""><?= Html::a('Menu Barang', ['/menu-barang']) ?></li>
           
            


        </ul>
        <div class="row">

            <div class="col-lg-12">
                <div class="barang-index">
                    <?php // echo $this->render('_search', ['model' => $searchModel]); 
                    ?>

                    <div class="table-responsive">
                        <?= GridView::widget([
                            'dataProvider' => $dataProvider,
                            'columns' => [
                                [
                                    'class' => 'yii\grid\SerialColumn',
                                    'header' => 'No.'
                                ],

                                //    'id',
                                'nama_barang',
                                'menu_barang',
                                [
                                    'attribute' => 'satuan',
                                    'contentOptions' => ['class' => 'text-left'],
                                    'value' => function($model) {
                                        $datasatuan=\common\models\SatuanBarang::find()->where(['id'=>$model->satuan])->one();
                                        return $datasatuan->keterangan;
                                    }
                                ],
                                [
                                    'attribute' => 'id_kategori',
                                    'contentOptions' => ['class' => 'text-left'],
                                    'value' => function($model) {
                                        $datakategori=\common\models\KategoriBarang::find()->where(['id'=>$model->id_kategori])->one();
                                        if($datakategori){
                                            return $datakategori->keterangan;
                                        }
                                        
                                    }
                                ],
                              //  'satuan',
                                'jumlah_barang',
                                'merk_barang',
                               
                                // 'id_user',

                                ['class' => 'yii\grid\ActionColumn'],
                            ],
                        ]); ?>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

backend/views/barang/pesanan-barang.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\money\MaskMoney;
/* @var $this yii\web\View */
/* @var $model common\models\Barang */

$modelName = 'Barang';
$this->title = 'Pemesanan Barang | ' ;
$this->params['breadcrumbs'][] = ['label' => 'Barang', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Pemesanan Barang';
?>

<div class="box-header">
    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
</div>
<div class="box">
    <div class="box-body">
    <ul class="nav nav-tabs">
            <li class=""><?= Html::a('Data Barang', ['/barang']) ?></li>

            <li class=""><?= Html::a('Satuan Barang', ['/satuan-barang']) ?></li>

            <li class=""><?= Html::a('Kategori Barang', ['/kategori-barang']) ?></li>
            <li class=""><?= Html::a('Pesanan Barang', ['/barang/pesanan']) ?></li>
            <li class=""><?= Html::a('Menu Barang', ['/menu-barang']) ?></li>
           
            


        </ul>
        <div class="row">
            <div class="col-md-12">
                <div class="box-header">
                    <h3 class="box-title"><?= 'Data Pesanan Barang' ?></h3>
                </div>
                <table class="table table-bordered table-hover table-responsive table-striped" cellpadding="6" cellspacing="1" style="width:100%" border="1">
                    <thead style="background-color: #7fc6b6;">

                        <tr>
                            <th>No</th>
                            <th>Nama Pelanggan</th>

                            <th>Provinsi</th>
                            <th>Kota/kabupaten</th>
                            
                            <th>Alamat</th>
                            <th>Jenis Pembayaran</th>
                            <th>Action</th>


                        </tr>
                    </thead>

                
                        <tr>
                            <td>1</td>
                            <td>Pelanggan 1</td>

                            <td>Jawa Barat</td>
                            <td>Bandung</td>
                            
                            <td>Jln. Proklamasi No 100</td>
                            <td>COD</td>
                            <td><a href="<?php echo \yii\helpers\Url::to(['/barang/konfirmasi-pemesanan', 'id' => 1]); ?>" target="_Blank" ><?php echo 'Konfirmasi'; ?></a></td>


                        </tr>
                        <tr>
                        <td>2</td>
                            <td>Pelanggan 2</td>

                            <td>Jawa Barat</td>
                            <td>Bandung</td>
                            
                            <td>Jln. Proklamasi No 100</td>
                            <td>COD</td>
                            <td><a href="<?php echo \yii\helpers\Url::to(['/barang/konfirmasi-pemesanan', 'id' => 1]); ?>" target="_Blank" ><?php echo 'Konfirmasi'; ?></a></td>



                        </tr>
                        <tr>
                        <td>3</td>
                            <td>Pelanggan 3</td>

                            <td>Jawa Barat</td>
                            <td>Bandung</td>
                            
                            <td>Jln. Proklamasi No 100</td>
                            <td>COD</td>
                            <td><a href="<?php echo \yii\helpers\Url::to(['/barang/konfirmasi-pemesanan', 'id' => 1]); ?>" target="_Blank" ><?php echo 'Konfirmasi'; ?></a></td>



                        </tr>
                    

                </table>
            </div>
        </div>


     
    </div>
</div>

backend/views/barang/tambah-keterangan.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use kartik\money\MaskMoney;
?>
<?php
 $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>


<div class="modal-header" style="background-color:#7fc6b6 ">
    <button type="button" class="close" data-dismiss="modal">&times;</button>


</div>
<div class="modal-body">
    <?php
    echo $form->field($modelketerangan, 'keterangan_warna')->textInput() ?>
    
    <?php
    echo $form->field($modelketerangan, 'keterangan_lainya')->textInput() ?>
    <?php
    echo $form->field($modelfoto, 'imageFiles[]')->fileInput(['multiple' => true,'accept' => 'image/*']) ?>

</div>
<div class="modal-footer" style="background-color:#7fc6b6 ">
<?= Html::submitButton('Simpan', ['class' => 'btn btn-primary', 'name' => 'simpan', 'value' => 'true']) ?>
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
<?php ActiveForm::end(); ?>

backend/views/barang/update.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Barang */

$modelName = 'Barang';
$this->title = 'Update Barang | ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Barang', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>

<div class="box-header">
    <h3 class="box-title"><?= Html::encode($this->title) ?></h3> 
</div>
<div class="box-body">
    <div class="row">
        <div class="col-lg-12">

            <div class="barang-update">

                <?= $this->render('_form', [
                'model' => $model,
                ]) ?>

            </div>

        </div>
    </div>
</div>

backend/views/barang/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\money\MaskMoney;
/* @var $this yii\web\View */
/* @var $model common\models\Barang */

$modelName = 'Barang';
$this->title = 'Barang | ' . $model->nama_barang;
$this->params['breadcrumbs'][] = ['label' => 'Barang', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box-header">
    <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
</div>
<div class="box">
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <div class="box-header">
                    <h3 class="box-title"><?= 'Data Barang' ?></h3>
                </div>
                <table class="table table-bordered table-hover table-responsive table-striped" cellpadding="6" cellspacing="1" style="width:100%" border="1">
                    <thead style="background-color: #7fc6b6;">

                        <tr>
                            <th>No</th>
                            <th>Nama Barang</th>

                            <th>Satuan Barang</th>
                            <th>Kategori Barang</th>
                            <th>Jumlah Barang</th>
                            <th>Merk Barang</th>


                        </tr>
                    </thead>

                    <?php
                    $no = 1;
                    if ($model)
                        $datasatuan = \common\models\SatuanBarang::find()->where(['id' => $model->satuan])->one();
                    $datakategori = \common\models\KategoriBarang::find()->where(['id' => $model->id_kategori])->one(); { ?>

                        <tr>
                            <td><?= $no; ?></td>
                            <td><?= $model->nama_barang; ?></td>

                            <td><?= $datasatuan->keterangan; ?></td>
                            <td><?= $datakategori->keterangan; ?></td>
                            <td><?= $model->jumlah_barang; ?></td>
                            <td><?= $model->merk_barang; ?></td>


                        </tr>
                    <?php } ?>

                </table>
            </div>
        </div>


        <div class="row">
            <div class="col-md-6">
                <div class="barang-form">

                    <?php
                    $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>


                    <div class="col-md-6">
                        <?= $form->field($modelukuran, 'ukuran')->textInput(['maxlength' => true]) ?>

                    </div>
                    <div class="col-md-6">
                        <?= $form->field($modelukuran, 'jumlah_barang')->textInput(['maxlength' => true]) ?>

                    </div>
                    <div class="col-md-6">
                        <?= $form->field($modelukuran, 'harga_beli')->widget(
                            MaskMoney::classname(),
                            [
                                'options' => [
                                    // 'readOnly' => true,
                                    //  'id' => 'harga-dp'
                                ],
                                'pluginOptions' => [
                                    'prefix' => 'Rp. ',
                                    'suffix' => '',
                                    'affixesStay' => TRUE,
                                    'precision' => 0,
                                    'allowZero' => false,
                                    'allowNegative' => false,
                                    'placeholder' => 'HPS',
                                    //'readOnly'=>true,
                                ],
                            ]
                        );
                        ?>


                    </div>
                    <div class="col-md-6">
                        <?= $form->field($modelukuran, 'harga')->widget(
                            MaskMoney::classname(),
                            [
                                'options' => [
                                    // 'readOnly' => true,
                                    //  'id' => 'harga-dp'
                                ],
                                'pluginOptions' => [
                                    'prefix' => 'Rp. ',
                                    'suffix' => '',
                                    'affixesStay' => TRUE,
                                    'precision' => 0,
                                    'allowZero' => false,
                                    'allowNegative' => false,
                                    'placeholder' => 'HPS',
                                    //'readOnly'=>true,
                                ],
                            ]
                        );
                        ?>


                    </div>
                </div>

                <div class="col-md-6">
                    <?= $form->field($modelketeranganukuran, 'keterangan_warna')->textInput(['maxlength' => true]) ?>

                </div>
                <div class="col-md-6">
                    <?= $form->field($modelketeranganukuran, 'keterangan_lainya')->textInput(['maxlength' => true]) ?>

                </div>
                <div class="col-md-12">
                    <?= $form->field($modelfoto, 'imageFiles[]')->fileInput(['multiple' => true,'accept' => 'image/*']) ?>


                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?= Html::submitButton('Simpan', ['class' => 'btn btn-primary', 'name' => 'simpan', 'value' => 'true']) ?>
                        <a href="./index" class="btn btn-default">Selesai</a>
                    </div>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
            <div class="col-md-6">
                <div class="box-header">
                    <h3 class="box-title"><?= 'Keterangan Ukuran Barang' ?></h3>
                </div>
                <table class="table table-bordered table-hover table-responsive table-striped" cellpadding="6" cellspacing="1" style="width:100%" border="1">
                    <thead style="background-color: #7fc6b6;">

                        <tr>
                            <th width="5%">No</th>
                            <th width="25%">Ukuran Barang</th>
                            <th width="25%">Harga Beli</th>
                            <th width="25%">Harga Jual</th>
                            <th width="25%">Jumlah Barang</th>
                            <th width="25%">Action</th>
                        </tr>
                    </thead>

                    <?php
                    $no = 1;
                    foreach ($dataukuran as $key => $val) {
                    ?>
                        <tr>
                            <td><?= $no + $key; ?></td>

                            <td class="text-left"><?php echo $val->ukuran; ?></td>
                            <td class="text-left"><?php echo 'Rp.' . number_format($val->harga_beli); ?></td>
                            <td class="text-left"><?php echo 'Rp.' . number_format($val->harga); ?></td>
                            <td class="text-left"><?php echo $val->jumlah_barang; ?></td>
                            <td class="text-left"><a href="<?php echo \yii\helpers\Url::to(['/barang/tambah-keterangan', 'id' => $val->id,'idbarang'=>$model->id]); ?>" data-target="#modalvote" data-toggle="modal"><?php echo 'Tambah Ket'; ?></a><br><a href="<?php echo \yii\helpers\Url::to(['/barang/data-keterangan', 'id' => $val->id]); ?>" target="_Blank"><?php echo 'Views'; ?>,</a>
                            </td>





                        </tr>
                    <?php }
                    ?>
                </table>
            </div>
        </div>

    </div>
</div>
<div class="modal remote fade" id="modalvote">
    <div class="modal-dialog">
        <div class="modal-content loader-lg"></div>
    </div>
</div>