backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\Admin;
use common\models\Himpunan;
use common\models\LoginForm;
use common\models\SignupForm;
use common\models\User;
use yii\web\UploadedFile;
use yii\imagine\Image;

/**
 * Site controller
 */
class SiteController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'signup', 'error','tambah-baru','master-aset','inventarisasi','stock-opname'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'profile', 'profile-photo', 'change-password','rubah'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            //            'error' => [
            //                'class' => 'yii\web\ErrorAction',
            //            ],
        ];
    }

    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            if (Yii::$app->user->id) {
                $this->layout = 'main';
            } else {
                $this->layout = 'login';
            }
            return $this->render('error', ['exception' => $exception]);
        }
    }

    public function actionRubah(){
        $datauser=  User::find()->all();
        foreach($datauser as $key=>$val){
            if($val->jabatan){
                $jabatan=  \common\models\Jabatan::find()->where(['id'=>$val->jabatan])->one();
                $val->jabatan=$jabatan->nama;
                $val->save(false);
            }
            if($val->pangkat){
                $pangkat=  \common\models\Pangkat::find()->where(['id'=>$val->pangkat])->one();
                $val->pangkat=$pangkat->nama;
                $val->save(false);
                
            }
            if($val->kesatuan){
                $kesatuan=  \common\models\Kesatuan::find()->where(['id'=>$val->kesatuan])->one();
                $val->kesatuan=$kesatuan->nama;
                $val->save(false);
            }
        }
    }
    
    public function actionChangePassword()
    {
        $user = \common\models\User::findOne(Yii::$app->user->id);
        $user->scenario = 'change_password';

        // var_dump($user);die;
        $loadedPost = $user->load(Yii::$app->request->post());

        if ($loadedPost && $user->validate()) {
            $user->password = $user->newPassword;

            if ($user->save(false)) {
                Yii::$app->session->setFlash('success', 'Password Berhasil Diperbarui');
                return $this->refresh();
            }
        }

        return $this->render("change-password", [
            'user' => $user,
        ]);
    }

    public function actionProfile()
    {
        $model =  User::findOne(Yii::$app->user->id);

        if ($model->load(Yii::$app->request->post())) {
            $model->input_photo = UploadedFile::getInstance($model, 'input_photo');

            if ($model->input_photo) {
                $photo = time() . $model->username . $model->input_photo->baseName . '.' . $model->input_photo->extension;
                $model->photo = $photo;
                if ($model->save()) {
                    if ($model->input_photo->saveAs(Yii::getAlias('@home/uploads/profile_photo/') . $photo)) {
                        $val = Image::thumbnail(Yii::getAlias('@home/uploads/profile_photo/') . $photo, 320, 320)
                            ->save(Yii::getAlias('@home/uploads/profile_photo/') . 'thumb-' . $photo, ['quality' => 50]);
                        if ($val) {
                            return $this->redirect('profile');
                        }
                    }
                }
            } else {
                if ($model->save()) {
                    return $this->redirect('profile');
                }
            }
        }
        return $this->render('profile', [
            'model' => $model,
        ]);
    }
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
    public function actionMasterAset()
    {
         $model=new \common\models\KartuKontrol();
        return $this->render('master-aset', [
            'model'=>$model,
           // 'daftarkartukontrol'=>$daftarkartukontrol,
                    
        ]);
    }
     public function actionInventarisasi()
    {
         $model=new \common\models\KartuKontrol();
        return $this->render('master-aset', [
            'model'=>$model,
           // 'daftarkartukontrol'=>$daftarkartukontrol,
                    
        ]);
    }
     public function actionStockOpname()
    {
         $model=new \common\models\KartuKontrol();
        return $this->render('master-aset', [
            'model'=>$model,
           // 'daftarkartukontrol'=>$daftarkartukontrol,
                    
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin($username = null)
    {
        $this->layout = 'login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $model->bilangan_pertama=rand(10,99);
        $model->bilangan_kedua=rand(1,10);
        $model->username = $username;
         if ($model->load(Yii::$app->request->post())) {
            $datahasil=$model->bilangan_pertama+$model->bilangan_kedua;
           // print_r($datahasil);die();
           if($model->bilangan_hasil == $datahasil){
               $model->login();
            return $this->goBack();
           }else{
                return $this->redirect('login');
           }
            
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionSignup()
    {
        $this->layout = 'login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->role = 5;
            if ($user = $model->signup()) {
                $user = User::findOne(['username' => $model->username]);
                $modell = new Himpunan();
                $modell->id_himpunan = $user->id;
                $modell->nama_himpunan = $model->nama;
                $modell->id_pembina = $model->id_pembina;
                $modell->ket_himpunan = $model->ket_himpunan;

                if ($modell->save()) {
                    return $this->redirect(['login', 'username' => $model->username]);
                }
                return $this->redirect(['login', 'username' => $model->username]);
            }
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }
public function actionTambahBaru(){
        {
       
        $model = new \common\models\SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->role='vendor';
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->renderAjax('daftar', [
            'model' => $model,
        ]);
    }
}
    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionProfilePhoto($inline = false)
    {
        $user = Yii::$app->user->identity;

        if ($user) {
            $path = \Yii::getAlias('@home') . '/uploads/profile_photo/thumb-';
            $file_download = $path . $user->photo;
            $fake_filename = $user->photo;
            $file_default = $path . 'default.png';
            $fake_filename_default = 'default.png';
            $response = Yii::$app->getResponse();

            if ($file_download && $fake_filename) {
                $response->sendFile($file_download, $fake_filename, ['inline' => $inline]);
            } else {
                $response->sendFile($file_default, $fake_filename_default, ['inline' => $inline]);
            }
        } else {
            throw new \yii\web\NotFoundHttpException('File not found');
        }
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use common\models\Barang;
use common\models\FotoBarang;
use common\models\KegiatanSearch;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\MenuBarang;
use common\models\SpesifikasiBarang;
use common\models\UkuranBarang;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionError()
    {

        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            if (Yii::$app->user->id) {
                $this->layout = 'main';
            } else {
                $this->layout = 'error';
            }
            return $this->render('error', ['exception' => $exception]);
        }
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */


    public function actionIndex()
    {
        $databarang1 = Barang::find()->orderBy('id DESC')->limit(50)->all();
        $databarang2 = Barang::find()->orderBy('id DESC')->limit(500)->all();
        $menubarang = MenuBarang::find()->all();
        // print_r($databarang);die();
        $datafototerbaru = FotoBarang::find()->orderBy('id DESC')->limit(7)->all();

        return $this->render('index', [
            'databarang2' => $databarang2,
            'menubarang' => $menubarang,
            'databarang1' => $databarang1,
            'datafototerbaru' => $datafototerbaru,
        ]);
    }
    public function actionDetailProduct($id)
    {
      
        $dataproduct = Barang::find()->where(['id' => $id])->one();
        $datafoto=FotoBarang::find()->where(['id_barang'=>$id])->all();
        $dataukuran=UkuranBarang::find()->where(['id_barang'=>$id])->all();
        return $this->render('detail-product', [
            'dataukuran'=>$dataukuran,
            'datafoto'=>$datafoto,
            'dataproduct' => $dataproduct,
        ]);
    }
    public function actionKeranjang()
    {
        // die();
        return $this->render('keranjang', []);
    }
    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        throw new NotFoundHttpException('The requested page does not exist.');
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        throw new NotFoundHttpException('The requested page does not exist.');
        $model = new \common\models\SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

backend/views/site/change-password.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

$this->title = 'Password';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box-body"> 
    <div class="row">
        <div class="col-md-3">

            <!-- Profile Image -->
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img class="profile-user-img img-responsive" src="<?= Url::toRoute(['site/profile-photo', 'inline' => true]) ?>" alt="User profile picture" style="background-color: #333333;">

                    <h3 class="profile-username text-center"></h3>

                    <p class="text-muted text-center"></p>

                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item text-center">
                            <b><?= $user->name ?></b>
                        </li>
                        <li class="list-group-item text-center">
                            <b><?= $user->email ?></b>
                        </li>
                    </ul>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <div class="col-md-9">
            <div class="site-index">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li><?=
                            Html::a('Profile', Url::toRoute(['site/profile']), [
                                'class' => 'btn btn-transparent'
                            ])
                            ?></li>
                        <li class="active"><a href="#set" data-toggle="tab">Password</a></li>
                    </ul>
                    <div class="tab-content">

                        <!--/.tab-pane -->
                        <div class="active tab-pane" id="set">

                            <div class="user-form">
                                <div class="box-body">
                                    <div class="col-lg-4 admin-menu-left-line">
                                        <?php $form = ActiveForm::begin(); ?>

                                        <?= $form->field($user, 'currentPassword')->passwordInput() ?>
                                        <?= $form->field($user, 'newPassword')->passwordInput() ?>
                                        <?= $form->field($user, 'newPasswordConfirm')->passwordInput() ?>


                                        <div class="form-group">
                                            <?= Html::submitButton($user->isNewRecord ? 'Tambah' : 'Ganti Password', ['class' => $user->isNewRecord ? 'btn btn-success' : 'btn btn-success']) ?>
                                            <a href="<?php echo Url::toRoute('/site'); ?>" class="btn btn-primary"> Cancel</a>
                                        </div>

                                        <?php ActiveForm::end(); ?>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/.tab-content -->
                </div>
                <!--/.nav-tabs-custom -->
            </div>
        </div>
    </div>
</div>

backend/views/site/daftar.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use kartik\money\MaskMoney;
?>
<?php
$form = ActiveForm::begin();
?>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
.w3-button {width:150px}
</style>

<div class="modal-header" style="background-color:#d2ddde ">
    <button type="button" class="close" data-dismiss="modal">&times;</button>

</div>
<div style="padding-bottom:15px">
     <img class="img-responsive center-block" src="<?= Yii::getAlias('@web/background/logo2.png') ?>" alt="logo polda" width="80px;">
</div>
<h4 class="login-box-msg">
    Signup Sistim Pengadaan
 
</h4>
<div class="modal-body">
    <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'email') ?>
    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

</div>
<div class="modal-footer" style="background-color:#d2ddde ">
    <?= Html::submitButton('Simpan', ['class' => 'w3-button w3-border w3-hover-blue']) ?>
    <button type="button" class="w3-button w3-border w3-hover-red" data-dismiss="modal">Close</button>
</div>
<?php ActiveForm::end(); ?>

backend/views/site/error.php
<?php
/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = '#' . $exception->statusCode;
?>

<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="site-error">

                            <div class="alert alert-danger">
                                <?= nl2br(Html::encode($exception->getMessage())) ?>
                            </div>

                            <p>
                                The above error occurred while the Web server was processing your request.
                            </p>
                            <p>
                                Please contact us if you think this is a server error. Thank you.
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/site/header-menu.php
<?php

use yii\helpers\Html;
?>
<ul class="nav nav-tabs">
    <li class=""><?= Html::a('Data Barang', ['/barang']) ?></li>

    <li class=""><?= Html::a('Satuan Barang', ['/satuan-barang']) ?></li>

    <li class=""><?= Html::a('Kategori Barang', ['/kategori-barang']) ?></li>



</ul>

backend/views/site/header.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\TabelSekolahSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */


?>

<div class="box-header">
    
     <div class="pull-left">
        <a class="btn btn-primary btn-sm" href="<?= Url::toRoute(['/site/master-aset']) ?>">Master Aset</a>
        <a class="btn btn-primary btn-sm" href="<?= Url::toRoute(['/site/inventarisasi']) ?>">Inventarisasi</a>
        <a class="btn btn-primary btn-sm" href="<?= Url::toRoute(['/site/stock-opname']) ?>">Stock Opname</a>
        


    </div>
   
</div>

backend/views/site/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'E-COMERS';
?>
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Welcome to Dashboard</h3>
            </div>
            <div class="box-body">
                <div class="box-widget widget-user">
                    <div class="widget-user-header" style="background-color: #7fc6b6;">
                        <h3 class="widget-user-username" style="color: white;"><?= Yii::$app->user->identity->name ?></h3>
                        <h5 class="widget-user-desc" style="color: white;">Administrator</h5>
                    </div>
                    <div class="widget-user-image">
                        <img class="img-circle" src="<?= Url::toRoute(['/site/profile-photo', 'inline' => true]) ?>" style="height: 90px; max-height: 90px; background-color: #333333;" alt="User Avatar">
                    </div>
                    <div class="box-footer" style="padding-bottom:0px">
                        <div class="row">
                            <center><br>
                                <p style="width:90%">Berikut data informasi detail akun anda saat ini : </p>
                            </center>
                        </div>
                    </div>
                </div>
                <div class="col-lg-offset-3 col-lg-6">
                    <div class="row">
                        <div class="col-lg-4 text-bold">Name</div>
                        <div class="col-lg-8"><?= Yii::$app->user->identity->name ?></div>
                        <div class="col-lg-4 text-bold">Username</div>
                        <div class="col-lg-8"><?= Yii::$app->user->identity->username ?></div>
                        <div class="col-lg-4 text-bold">Email</div>
                        <div class="col-lg-8"><?= Yii::$app->user->identity->email ?></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-lg-12">
                            <a class="btn btn-block btn-sm btn-primary" href="<?= Url::toRoute(['/site/profile']) ?>">Profil</a><br>

                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

backend/views/site/profile.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use kartik\date\DatePicker;

/* @var $this yii\web\View */

$this->title = 'Profile';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box-body">
    <div class="row">
        <div class="col-md-3">
            <!-- Profile Image -->
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img class="profile-user-img img-responsive" src="<?= Url::toRoute(['site/profile-photo', 'inline' => true]) ?>" alt="User profile picture" style="background-color: #333333;">

                    <h3 class="profile-username text-center"></h3>

                    <p class="text-muted text-center"></p>

                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item text-center">
                            <b><?= $model->name ?></b>
                        </li>
                        <li class="list-group-item text-center">
                            <b><?= $model->email ?></b>
                        </li>
                    </ul>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box-body -->
        </div>
        <div class="col-md-9">
            <div class="site-index">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#set" data-toggle="tab">Profile</a></li>
                        <li><?=
                                Html::a('Password', Url::toRoute(['site/change-password']), [
                                    'class' => 'btn btn-transparent'
                                ])
                            ?></li>
                    </ul>
                    <div class="tab-content">

                        <!--/.tab-pane -->
                        <div class="active tab-pane" id="set">
                            <div class="kasi-form">

                                <div class="box-body">
                                    <div class="col-lg-4 admin-menu-left-line">
                                        <?php
                                        $form = ActiveForm::begin([
                                            'fieldConfig' => [
                                                //                                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                                                'options' => [
                                                    'label' => 'col-sm-4',
                                                    'offset' => 'col-sm-offset-4',
                                                    'wrapper' => 'col-sm-8',
                                                    'error' => '',
                                                    'hint' => '',
                                                ],
                                            ],
                                        ]);
                                        ?>

                                        <div class="form-group">
                                            <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'class' => 'form-control']) ?>
                                        </div>
                                        <div class="form-group">
                                            <?= $form->field($model, 'username')->textInput(['class' => 'form-control']) ?>
                                        </div>
                                        <div class="form-group">
                                            <?= $form->field($model, 'email')->textInput(['class' => 'form-control']) ?>
                                        </div>
                                        <div class="form-group">
                                            <?= $form->field($model, 'input_photo')->fileInput(['accept' => 'image/*']) ?>
                                        </div>
                                        <div class="form-group">
                                            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                                        </div>



                                        <?php ActiveForm::end(); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--/.tab-content -->
                </div>
                <!--/.nav-tabs-custom -->
            </div>
        </div>
    </div>
</div>